# 内部转发请求配置，0值为无超时 单位为秒
# connTimeout: 用户连接超时
# idleConnTimeout: 空闲连接超时
# responseHeaderTimeout: 响应头超时
server-conn:
  connTimeout: 0
  idleConnTimeout: 0
  responseHeaderTimeout: 0

#white-addr:
#  - '127.0.0.1'
#  - 'xxx.xxx.xxx.xxx'

# 开启特殊标记增强
flags: true

# 图片访问
domain: "https://all.zeabur.app"

# 内调llm，用于绘图时文本转tags
llm:
  base-url: "http://127.0.0.1:8081"
  model: "command-r-plus"
  token: "kUbPWLagtquZkTAp9y3c4aFqDMRMmLMLuiXZNSVs"

# lmsys fn、 trigger，支持多模型参数映射，json格式
lmsys: |
  {
    "claude-3-5-sonnet-20240620": [ 70, 124 ]
  }

# hf 绘图接口配置化
# 若旧接口不可用，可以到huggingface上查找同类型的接口配置
# 参数替换：{{prompt}}、{{negative_prompt}}、{{sampler}}、{{style}}、{{seed}}
hf:
  animagine-xl-3.1:
    base-url: https://boboiazumi-animagine-xl-3-1.hf.space
    fn: [5, 61]
    data: '[
      "{{prompt}}",
      "{{negative_prompt}}",
      {{seed}},
      1024,
      1024,
      8,
      35,
      "{{sampler}}",
      "1024 x 1024",
      "{{style}}",
      "Standard v3.1",
      true,
      0.55,
      1.5,
      false,
      false,
      null,
      0.65
    ]'
  dalle-4k:
    base-url: https://mukaist-dalle-4k.hf.space
  dalle-3-xl:
    base-url: https://ehristoforu-dalle-3-xl-lora-v2.hf.space

# gemini 自定义安全设置
google:
  tc: true # 是否使用提示词实现的toolCall
#  safes:
#    - category: HARM_CATEGORY_HARASSMENT
#      threshold: BLOCK_NONE

# cohere 自定义安全设置，目前仅兼容 Command R 08-2024、Command R+ 08-2024 及更新机型
cohere:
  safety: CONTEXTUAL # NONE | CONTEXTUAL | STRICT

bing:
  base-url: "https://edgeservices.bing.com/edgesvc"

interpreter:
  base-url: http://127.0.0.1:8000
  echo-code: true
  ws: true

custom-llm:
  - base-url: https://models.inference.ai.azure.com
    prefix: github
    use-proxies: true
    tc: true
  #- base-url: http://127.0.0.1:8080/v1
    #prefix: custom

# toolCall 默认配置化; 在 flags 关闭时也可用
toolCall:
  id: -1
  enabled: true
  tasks: true

# 图片放大，domain需要公网可访问的地址
# key请到https://bigjpg.com获取，每月30次免费
# 目前注册没有限制，可配置多个key轮询
#magnify:
#  - "xxx"

# 用于处理llm响应时的内容
# find: 开头匹配
# end: 结束匹配
# content: 正则处理,用于正则替换。例如实现CoT内容屏蔽，达到类似openai_o1的效果
# desc: 可以在find命中时给前端反馈一些简单文字
matcher:
 - find: <!-- Attack
   end: -->
   content: "<!-- Attack [\\s\\S]+ -->:"
 - find: I do not
   end: ":\n"
   content: "I do not [\\s\\S]+:\n"
 - find: age with prompt injection
   end: ":\n"
   content: "age with prompt injection [\\s\\S]+:\n"
 - find: <thinking>
   end: </thinking>
   content: "<thinking>[\\s\\S]+<\\/thinking>:"
