# 内部转发请求配置，0值为无超时 单位为秒
# connTimeout: 用户连接超时
# idleConnTimeout: 空闲连接超时
# responseHeaderTimeout: 响应头超时
server-conn:
  connTimeout: 0
  idleConnTimeout: 0
  responseHeaderTimeout: 0

# 开启特殊标记增强
flags: true

interpreter:
  baseUrl: http://127.0.0.1:8000
  echoCode: true
  ws: true

custom-llm:
  baseUrl: http://127.0.0.1:8080

# toolCall 默认配置化; 在 flags 关闭时也可用
toolCall:
  id: -1
  enabled: true
  tasks: true