# 内部转发请求配置，0值为无超时 单位为秒
# connTimeout: 用户连接超时
# idleConnTimeout: 空闲连接超时
# responseHeaderTimeout: 响应头超时
server-conn:
  connTimeout: 0
  idleConnTimeout: 0
  responseHeaderTimeout: 0

white-addr:
#  - '127.0.0.1'
#  - 'xxx.xxx.xxx.xxx'

# 开启特殊标记增强
flags: true

# 图片访问
domain: "https://all.deem.love"

# 内调llm，用于绘图时文本转tags
llm:
  base-url: "http://127.0.0.1:8081"
  model: "command-r-plus"
  token: "kUbPWLagtquZkTAp9y3c4aFqDMRMmLMLuiXZNSVs"

# lmsys fn、 trigger
lmsys: [49 , 109]

# hf 绘图接口配置化
# 若旧接口不可用，可以到huggingface上查找同类型的接口配置
# 参数替换：{{prompt}}、{{negative_prompt}}、{{sampler}}、{{style}}、{{seed}}
hf:
  animagine-xl-3.1:
    base-url: https://boboiazumi-animagine-xl-3-1.hf.space
    fn: [5, 61]
    data: '[
      "{{prompt}}",
      "{{negative_prompt}}",
      {{seed}},
      1024,
      1024,
      8,
      35,
      "{{sampler}}",
      "1024 x 1024",
      "{{style}}",
      "Standard v3.1",
      true,
      0.55,
      1.5,
      false,
      false,
      null,
      0.65
    ]'
  dalle-4k:
    base-url: https://mukaist-dalle-4k.hf.space
  dalle-3-xl:
    base-url: https://ehristoforu-dalle-3-xl-lora-v2.hf.space

# gemini 自定义安全设置
google:
#  safes:
#    - category: HARM_CATEGORY_HARASSMENT
#      threshold: BLOCK_NONE

bing:
  base-url: "https://edgeservices.bing.com/edgesvc"

claude:
  pad: 0
  cookies:
    - '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'
    - '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'
    - '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'

interpreter:
  base-url: http://127.0.0.1:8000
  echoCode: true
  ws: true

custom-llm:
  - base-url: http://127.0.0.1:8080/v1
    prefix: custom
    use-proxies: false
    tc: false

# toolCall 默认配置化; 在 flags 关闭时也可用
toolCall:
  id: -1
  enabled: true
  tasks: true

# 图片放大，domain需要公网可访问的地址
# key请到https://bigjpg.com获取，每月30次免费
# 目前注册没有限制，可配置多个key轮询
#magnify:
#  - "xxx"